#!/bin/bash

LINEBREAK="*****************************************************************"
VERSION=0
echo "which jekyll = $(which jekyll)"
printf "Checking Jekyll... "

if VERSION=$(jekyll --version)
then
     echo "$VERSION is installed on this system."
else
     echo "$VERSION"
     echo "$LINEBREAK"
     echo "Oops! It looks like you don't yet have Jekyll, lets install it!"
     echo "Running command: \"sudo gem install jekyll\""
     echo "$LINEBREAK"
     sudo gem install jekyll
     if test "$?" != "0"
     then
          echo "$LINEBREAK"
          echo "Jekyll install failed... It needs to be installed as a super-user on your system, which"
          echo "requires your password. You can run \"sudo gem install jekyll\" yourself to install Jekyll."
          echo "You can also see their website at: \"https://jekyllrb.com/docs/installation/\" for more information"
          echo "$LINEBREAK"
          exit 113
     else
          echo "$LINEBREAK"
          echo "Jekyll has been installed on this system..."
          echo "Proceeding to build..."
          echo "$LINEBREAK"
     fi
fi

exit 0
